tickers:
- NVDA
- AAOI
- ACMR
- ACNT
- AEHR
- AES
- AGM
- AII
- APP
- ASIC
- ASIX
- ASML
- BLNE
- CBLL
- CBNA
- CCLD
- CFNB
- COUR
- CRDF
- CRDO
- DOCU
- EDSA
- FICO
- FLYW
- FRO
- HRTG
- HYNE
- ICE
- IESC
- IVFH
- JMIA
- LB
- MIAX
- MICC
- MKL
- MLP
- MNTN
- MRX
- NN
- NVTS
- NWSA
- OMAB
- OPY
- PFSB
- PKBK
- PLBY
- SATS
- SBMW
- SHLS
- SHMD
- SNBR
- SNAP
- SNWV
- SOLS
- TIC
- TPB
- TSM
- TWST
- UMC
- UVE
- VNDA
- VOD
- VRME
- WBI
- ZM
- WSBF
- VTRS
- FTRK
- CEIN
- INV
- RBNE
- CTXR
- CTOR
- AIRT
- ALTO
- SKM
- MKTW
- KMFG
- IMRX
- COHN
- COBA
- HUN
- DOW
- BAK
- LYB
- OLN
- LXU
- ERII
- IFOS.V
- LGO
- REOP
- KNOP
- SU
- QURE
- CLPT
- TROX
- CC
- KLXE
- ACDC
- BGC
- EVC
- FCEL
- LBRT
- IBIO
- RLMD
- ABEO
- KRRO
- LSTA
- INM
- PLX
- KROS
- ALLR
- IEHC
- CLMT
- AMRC
- PROP
- DIS
- KLNG
- VTIX
- HMR.V
- PRLD
- TNXP
- CBR.V
- BNTC
- APYX
- FEMY
- PTX.V
- ENA.V
